TAROT_CARDS = [
    # Major Arcana
    {"name": "The Fool", "upright": "Beginnings, innocence, spontaneity, a free spirit.", "reversed": "Holding back, recklessness, risk-taking."},
    {"name": "The Magician", "upright": "Manifestation, resourcefulness, power, inspired action.", "reversed": "Manipulation, poor planning, untapped talents."},
    {"name": "The High Priestess", "upright": "Intuition, sacred knowledge, divine feminine, the subconscious mind.", "reversed": "Secrets, disconnected from intuition, withdrawal, silence."},
    {"name": "The Empress", "upright": "Femininity, beauty, nature, nurturing, abundance.", "reversed": "Creative block, dependence on others."},
    {"name": "The Emperor", "upright": "Authority, structure, control, fatherhood.", "reversed": "Domination, excessive control, inflexibility, discipline lost."},
    {"name": "The Hierophant", "upright": "Spiritual wisdom, tradition, conformity, morality.", "reversed": "Personal beliefs, freedom, challenging tradition."},
    {"name": "The Lovers", "upright": "Love, harmony, partnerships, choices, alignment.", "reversed": "Disharmony, imbalance, misalignment of values."},
    {"name": "The Chariot", "upright": "Control, willpower, success, action, determination.", "reversed": "Self-discipline lost, opposition, lack of direction."},
    {"name": "Strength", "upright": "Courage, persuasion, influence, compassion.", "reversed": "Self-doubt, weakness, insecurity, raw emotion."},
    {"name": "The Hermit", "upright": "Soul-searching, introspection, inner guidance.", "reversed": "Isolation, loneliness, withdrawal."},
    {"name": "Wheel of Fortune", "upright": "Good luck, karma, life cycles, destiny, turning points.", "reversed": "Bad luck, resistance to change, breaking cycles."},
    {"name": "Justice", "upright": "Fairness, truth, law, cause and effect.", "reversed": "Unfairness, dishonesty, lack of accountability."},
    {"name": "The Hanged Man", "upright": "Pause, surrender, letting go, new perspectives.", "reversed": "Delays, resistance, stalling, indecision."},
    {"name": "Death", "upright": "Endings, change, transformation, transition.", "reversed": "Resistance to change, personal transformation, inner purging."},
    {"name": "Temperance", "upright": "Balance, moderation, patience, purpose.", "reversed": "Imbalance, excess, lack of long-term vision."},
    {"name": "The Devil", "upright": "Shadow self, attachment, addiction, restriction, sexuality.", "reversed": "Releasing limiting beliefs, exploring dark thoughts, detachment."},
    {"name": "The Tower", "upright": "Sudden change, upheaval, chaos, revelation, awakening.", "reversed": "Personal transformation, fear of change, averting disaster."},
    {"name": "The Star", "upright": "Hope, faith, purpose, renewal, spirituality.", "reversed": "Lack of faith, despair, self-trust lost, disconnection."},
    {"name": "The Moon", "upright": "Illusion, fear, anxiety, subconscious, intuition.", "reversed": "Release of fear, repressed emotion, inner confusion."},
    {"name": "The Sun", "upright": "Positivity, fun, warmth, success, vitality.", "reversed": "Inner child, feeling down, unrealistic expectations."},
    {"name": "Judgement", "upright": "Judgement, rebirth, inner calling, absolution.", "reversed": "Self-doubt, inner critic, ignoring the call."},
    {"name": "The World", "upright": "Completion, integration, accomplishment, travel.", "reversed": "Seeking personal closure, short-cuts, delays."},

    # Minor Arcana – Wands
    {"name": "Ace of Wands", "upright": "Inspiration, new opportunities, growth, potential.", "reversed": "An emerging idea, lack of direction, distractions, delays."},
    {"name": "Two of Wands", "upright": "Future planning, progress, decisions, discovery.", "reversed": "Fear of unknown, lack of planning."},
    {"name": "Three of Wands", "upright": "Expansion, foresight, overseas opportunities.", "reversed": "Playing small, lack of foresight, unexpected delays."},
    {"name": "Four of Wands", "upright": "Celebration, joy, harmony, relaxation, homecoming.", "reversed": "Personal celebration, inner harmony, conflict with family."},
    {"name": "Five of Wands", "upright": "Conflict, disagreements, competition, tension.", "reversed": "Inner conflict, avoiding conflict, tension release."},
    {"name": "Six of Wands", "upright": "Success, public recognition, progress, self-confidence.", "reversed": "Private achievement, fall from grace, egotism."},
    {"name": "Seven of Wands", "upright": "Challenge, competition, perseverance.", "reversed": "Giving up, overwhelmed, overly protective."},
    {"name": "Eight of Wands", "upright": "Movement, fast paced change, action, alignment.", "reversed": "Delays, frustration, resisting change."},
    {"name": "Nine of Wands", "upright": "Resilience, courage, persistence, test of faith.", "reversed": "Exhaustion, fatigue, overly defensive."},
    {"name": "Ten of Wands", "upright": "Burden, extra responsibility, hard work, completion.", "reversed": "Doing it all, carrying too much, release."},
    {"name": "Page of Wands", "upright": "Inspiration, ideas, discovery, limitless potential.", "reversed": "Newly-formed ideas, redirecting energy, self-limiting beliefs."},
    {"name": "Knight of Wands", "upright": "Energy, passion, inspired action, adventure.", "reversed": "Haste, scattered energy, delays, frustration."},
    {"name": "Queen of Wands", "upright": "Courage, confidence, independence, determination.", "reversed": "Self-respect, introversion, repressed creativity."},
    {"name": "King of Wands", "upright": "Natural-born leader, vision, entrepreneur, honor.", "reversed": "Impulsive, overbearing, ineffective leadership."},

    # Minor Arcana – Cups
    {"name": "Ace of Cups", "upright": "Love, new relationships, compassion, creativity.", "reversed": "Self-love, intuition, repressed emotions."},
    {"name": "Two of Cups", "upright": "Unified love, partnership, mutual attraction.", "reversed": "Self-love, break-ups, disharmony, distrust."},
    {"name": "Three of Cups", "upright": "Celebration, friendship, creativity, collaborations.", "reversed": "Independence, alone time, hardcore partying."},
    {"name": "Four of Cups", "upright": "Meditation, contemplation, apathy, reevaluation.", "reversed": "Retreat, withdrawal, checking in for alignment."},
    {"name": "Five of Cups", "upright": "Regret, failure, disappointment, pessimism.", "reversed": "Moving on, acceptance, forgiveness."},
    {"name": "Six of Cups", "upright": "Revisiting the past, childhood memories, innocence.", "reversed": "Living in the past, forgiveness, lacking playfulness."},
    {"name": "Seven of Cups", "upright": "Opportunities, choices, wishful thinking, illusion.", "reversed": "Alignment, personal values, overwhelmed by choices."},
    {"name": "Eight of Cups", "upright": "Disappointment, abandonment, withdrawal, escapism.", "reversed": "Trying one more time, indecision, aimless drifting."},
    {"name": "Nine of Cups", "upright": "Contentment, satisfaction, gratitude, wish come true.", "reversed": "Inner happiness, materialism, dissatisfaction, indulgence."},
    {"name": "Ten of Cups", "upright": "Divine love, blissful relationships, harmony, alignment.", "reversed": "Disconnection, misaligned values, struggling relationships."},
    {"name": "Page of Cups", "upright": "Creative opportunities, intuitive messages, curiosity.", "reversed": "New ideas, doubting intuition, emotional immaturity."},
    {"name": "Knight of Cups", "upright": "Romance, charm, imagination, beauty.", "reversed": "Overactive imagination, unrealistic, jealous, moodiness."},
    {"name": "Queen of Cups", "upright": "Compassionate, caring, emotionally stable, intuitive.", "reversed": "Inner feelings, self-care, co-dependency."},
    {"name": "King of Cups", "upright": "Emotionally balanced, compassionate, diplomatic.", "reversed": "Emotional manipulation, moodiness, coldness."},

    # Minor Arcana – Swords
    {"name": "Ace of Swords", "upright": "Breakthroughs, new ideas, mental clarity, success.", "reversed": "Inner clarity, rethinking an idea, clouded judgment."},
    {"name": "Two of Swords", "upright": "Difficult decisions, weighing options, stalemate.", "reversed": "Indecision, confusion, information overload."},
    {"name": "Three of Swords", "upright": "Heartbreak, emotional pain, sorrow, grief, hurt.", "reversed": "Negative self-talk, releasing pain, optimism, forgiveness."},
    {"name": "Four of Swords", "upright": "Rest, relaxation, meditation, contemplation, recovery.", "reversed": "Exhaustion, burnout, deep contemplation, stagnation."},
    {"name": "Five of Swords", "upright": "Conflict, disagreements, competition, defeat, betrayal.", "reversed": "Reconciliation, making amends, past resentment."},
    {"name": "Six of Swords", "upright": "Transition, change, rite of passage, releasing baggage.", "reversed": "Personal transition, resistance to change, unfinished business."},
    {"name": "Seven of Swords", "upright": "Betrayal, deception, getting away with something.", "reversed": "Confession, acting strategically, turning a new leaf."},
    {"name": "Eight of Swords", "upright": "Negative thoughts, self-imposed restriction, imprisonment.", "reversed": "Self-limiting beliefs, inner critic, releasing fear."},
    {"name": "Nine of Swords", "upright": "Anxiety, worry, fear, depression, nightmares.", "reversed": "Inner turmoil, secrets, releasing worry, hope."},
    {"name": "Ten of Swords", "upright": "Painful endings, deep wounds, betrayal, loss, crisis.", "reversed": "Recovery, regeneration, resisting an inevitable end."},
    {"name": "Page of Swords", "upright": "New ideas, curiosity, thirst for knowledge, new ways of communicating.", "reversed": "Self-expression blocked, gossip, deception."},
    {"name": "Knight of Swords", "upright": "Ambitious, action-oriented, driven to succeed.", "reversed": "Restless, unfocused, burn-out, impulsive."},
    {"name": "Queen of Swords", "upright": "Independent, unbiased judgment, clear boundaries.", "reversed": "Overly emotional, easily influenced, cold-hearted."},
    {"name": "King of Swords", "upright": "Mental clarity, intellectual power, truth, authority.", "reversed": "Manipulative, abusive power, misuse of authority."},

    # Minor Arcana – Pentacles
    {"name": "Ace of Pentacles", "upright": "A new financial opportunity, prosperity, manifestation.", "reversed": "Lost opportunity, scarcity, lack of planning."},
    {"name": "Two of Pentacles", "upright": "Balance, adaptability, time management, priorities.", "reversed": "Overcommitted, disorganization, imbalance."},
    {"name": "Three of Pentacles", "upright": "Teamwork, collaboration, building, learning.", "reversed": "Disharmony, misalignment, working alone."},
    {"name": "Four of Pentacles", "upright": "Saving money, security, conservatism, scarcity mindset.", "reversed": "Over-spending, greed, self-protection, release."},
    {"name": "Five of Pentacles", "upright": "Financial loss, poverty, isolation, worry, insecurity.", "reversed": "Recovery, rebuilding wealth, improving security."},
    {"name": "Six of Pentacles", "upright": "Giving, receiving, generosity, sharing wealth.", "reversed": "Self-care, debt, one-sided charity."},
    {"name": "Seven of Pentacles", "upright": "Long-term view, sustainable results, perseverance.", "reversed": "Lack of long-term vision, limited success, impatience."},
    {"name": "Eight of Pentacles", "upright": "Apprenticeship, skill development, mastery.", "reversed": "Perfectionism, lacking ambition, uninspired work."},
    {"name": "Nine of Pentacles", "upright": "Abundance, luxury, self-sufficiency, financial independence.", "reversed": "Self-worth, hustling, over-investment in work."},
    {"name": "Ten of Pentacles", "upright": "Wealth, financial security, family, long-term success.", "reversed": "Financial failure, loneliness, loss."},
    {"name": "Page of Pentacles", "upright": "Manifestation, financial opportunity, skill development.", "reversed": "Lack of progress, procrastination, short-term focus."},
    {"name": "Knight of Pentacles", "upright": "Hard work, productivity, routine, conservatism.", "reversed": "Boredom, feeling stuck, perfectionism."},
    {"name": "Queen of Pentacles", "upright": "Nurturing, practical, providing financially, working parent.", "reversed": "Self-care, work–home conflict, financial dependence."},
    {"name": "King of Pentacles", "upright": "Wealth, business, leadership, security, abundance.", "reversed": "Greed, indulgence, stubbornness, exploitation."}
]
