DATE_IDEAS = [
    "A cozy coffee shop date ☕",
    "Karaoke night where you only sing duets 🎤",
    "Bowling but with ridiculous self-imposed challenges 🎳",
    "A fancy candlelit dinner at the most questionable fast-food place 🍔🕯️",
    "A stargazing adventure with a blanket fort in the back of a car 🌌",
    "Visiting a haunted house and pretending to be paranormal investigators 👻",
    "A chaotic mini golf game where every hole has a made-up rule ⛳",
    "A picnic but only with foods that start with the same letter 🍉🥪",
    "A thrift store challenge — pick outfits for each other to wear 👗",
    "A late-night drive blasting guilty pleasure songs 🚗🎶",
    "A trip to an arcade with a competition for the silliest prize 🎮",
    "A cooking date where you swap ingredients at random 🥘🎲",
    "An amusement park trip where you must ride the scariest ride first 🎢",
    "A spontaneous road trip with no destination planned 🗺️",
    "Ice cream taste test of the weirdest flavors you can find 🍦",
    "Attending a random local event you know nothing about 🎭",
    "Board game night but the loser has to perform a dare 🎲",
    "A paint and sip night, but swap canvases halfway through 🎨🍷",
    "Go to the zoo and pretend to be documentary narrators 🦁🎙️",
    "A beach day where you build the weirdest sandcastle possible 🏖️",
    "Movie night but you both have to watch a film you’ve never heard of 🎬",
    "Trying to make TikTok dance videos together 💃📱",
    "Laser tag but form a dramatic ‘spy backstory’ first 🔫🕶️",
    "Visiting IKEA and pretending to live in the showrooms 🛋️",
    "Dressing up in costumes for a completely normal dinner 🍽️😂",
    "A mystery food tour — blindfold taste test of snacks 🍱😋",
    "Roller skating in retro outfits 🛼",
    "A water balloon fight on a hot day 💦🎈",
    "Renting a karaoke booth and only singing dramatic breakup songs 🎤💔",
    "Going to an art gallery and inventing fake backstories for each painting 🖼️",
    "Having a cook-off with a random basket of ingredients (Iron Chef style) 🍳🔥"
]